### ISSUE TITLE
esphome has an Growatt component which could use your enhancement

### ISSUE THREAD

**Issue by osos** [nygma2004/growatt2mqtt#10]
Just wanted to make you aware that esphome has a preliminary growatt component.

https://esphome.io/components/sensor/growatt_solar.html
https://github.com/esphome/esphome/tree/dev/esphome/components/growatt_solar

Maybe it would be even easier to maintain etc to enhance the esphome component with the communications you have made here.

I think that would be a good place to merge the project as that will make it easily availble to the arduino/home-assistant community.

**Comment by nygma2004** [comment]
Well, it looks like ESPHome implemented the same what I did. To be honest, I don't see a point merging anything. If you are using home assistant just set up ESPHome and for pure MQTT one can use my project.
