### ISSUE TITLE
SetMaxOutputActive doesnt work

### ISSUE THREAD

**Issue by snzyeee** [nygma2004/growatt2mqtt#15]
Hi, as far as i can see, you can set the maximum inverter output with mqtt by the command /setMaxOutputActive but this doenst work. 

So i took a quick search in the code and found a line /setMaxOutput. Then i tried  /setmaxOutput and it worked.

**Comment by joe288** [comment]
Hi, That was a typo in the documentation. I corrected it in my fork and will make a pull request.
