### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by matthias-bs** [nygma2004/growatt2mqtt#19]
Hi, 
Thank you very much for providing this project!
I would like to use this for a LoRaWAN based variant. Which license applies to this project?
For most of my project, I'm favoring the MIT license.
Best regards
Matthias

**Comment by nygma2004** [comment]
Hi Matthias,
I have the MIT license to the project. I am new to all this I hope I done this right.
Best regards,
Csongor

**Comment by matthias-bs** [comment]
Hi Csongor,
Excellent! Thanks a lot!
Best regards
Matthias
