### ISSUE TITLE
Getting Error: Invalid slave ID

### ISSUE THREAD

**Issue by SHODK** [nygma2004/growatt2mqtt#2]
Hi,
What a great project you have made here, I follow you video and think I made a correct setup, however I get Error: Invalid slave ID on the MQTT
My Growatt is same as yours, MIN 3000TL-XE
I check the COM ID on Growatt it is set to 001
I try change it to 002 or 003 with the same change in Arduino sketch
I double check my wiring of Wemos D1 and TTl to RS-485 module, I have same 230V power supply as you show
No matter what I try it give me same error, do you have any idea where to look?

<img width="504" alt="MQTT Explorer - Invalid slave ID" src="https://user-images.githubusercontent.com/92098787/152653216-bcf94adf-d30c-4bd4-af83-09ecc37c20fc.png">

<img width="368" alt="Arduino-Growatt" src="https://user-images.githubusercontent.com/92098787/152653222-f0e38205-8f38-4c37-9323-58447329adcb.png">

**Comment by nygma2004** [comment]
OK, so this is interesting. In the log I can see messages saying that "Data MQTT Sent". So it is able to read data off the inverter from time to time. It is possible that the read rate is too quick for the inverter. That does not explain why it would send and invalid slave ID, but still. Can you change the UPDATE_MODBUS variable from 2 to for example 5 and test again?

**Comment by SHODK** [comment]
Thanks for the quick reply, it did not help increasing it to 5 or 10, however I did find the fault and it was my own, when compiling the Arduino sketch a few days ago, it gave an error on "mqtt.setBufferSize(1024)" so I commented it out, it turnout that my PubSubClient library was a old version 2.7.0, upgrading to 2.8.0 it could now compile without error, uploaded program and everything works now.
Again, thanks for a great program and video

**Comment by nygma2004** [comment]
Oh, wow, I did not know that the setBufferSize was only implemented in 2.8.0. Good catch. I needed this as the data payloads are very big.

**Comment by unimatrixZxero** [comment]
Adding a data-point here. I had that error as well initially, I noticed that one of the connections to the RS485-TTL wasn't very good. Fixed the connection and the issue resolved itself.  Specifically it was the DE -> D5 connection ( RS485-TTL -> ESP32 D1 Mini)

**Comment by no-Legend** [comment]
I'm facing the same problem with my MIC600, all the time I got that error.
Allready using the 2.8.0 version of PubSubClient and there is now warning during the compilation.

**Comment by nygma2004** [comment]
@no-Legend sorry but to be exact, are you getting the error on compiling the sketch?
Can you paste in the error that you get?
