### ISSUE TITLE
Growatt MOD 6000TL3-X 

### ISSUE THREAD

**Issue by Teppis88** [nygma2004/growatt2mqtt#27]
Have to say that this code works fine with this 6kw 3phase model. Only problem is that I can't get voltages from different phases.

Can I somehow scan all the messages that growat sends so I could check em if it sends them?

**Comment by nygma2004** [comment]
Yes you can. To make your life easier, maybe you can get a RS485 to USB dongle and you can access modbus directly on your laptop. It is easier to change the modbus parameters in a modbus tester program like Modbus Poll than changing the code, compile and upload. Just like other voltages, the voltage is stored on 0.1V, so you should look for values in 2200-2500 range.

**Comment by joe288** [comment]
You can query additional values ​​in the **growattInterface.cpp** in the **ReadInputRegisters()** function.
As an example you can see how **gridvoltage** is implemented.

![image](https://user-images.githubusercontent.com/20052129/233764897-f2fa0181-5de6-49b8-917f-d37ae334167e.png)

I think the values ​​you should be interested in are in the area.
![image](https://user-images.githubusercontent.com/20052129/233764952-ff910b59-6eca-4adf-8bfd-5e78b13438fb.png)

You have to test the value of the information that interests you.

Unfortunately, I only have the single-phase version and can't do it for you.

**Comment by joe288** [comment]
see changes from here https://github.com/wroadd/growatt2mqtt_for3phases

**Comment by Teppis88** [comment]
Thanks Joe288! That works :)
