### ISSUE TITLE
Sending setMaxOutput to MQTT

### ISSUE THREAD

**Issue by sstolk90** [nygma2004/growatt2mqtt#28]
Hi,

I would like to try this setting to reduce the power of the inverter in case of a negative energyprice when my battery is full.
In MQTT Explorer I tried to send this:

![image](https://user-images.githubusercontent.com/65487781/233649197-5f93aa8c-f4bd-43bf-bf62-085dcb1722b9.png)

![image](https://user-images.githubusercontent.com/65487781/233649324-044cdcd8-a5c1-4546-8628-4b6e38502389.png)

What am I doing wrong?
What is the syntax for the MQTT message?
I can not find any documentation in the code.

**Comment by nygma2004** [comment]
Let me add @joe288 as he added this functionality to my original code.

**Comment by sstolk90** [comment]
Since when is this in the code?
Because I think it's not in mine...

**Comment by joe288** [comment]
Hello,
the value is simply transferred in decimal. 
From 1-100%. 
![image](https://user-images.githubusercontent.com/20052129/233763998-2c52b749-9a55-4742-b47d-6d98ba7470b1.png)
You can also switch off the Growatt completely via setEnable.
![image](https://user-images.githubusercontent.com/20052129/233764012-a484c75e-37ff-4dbe-988c-c1e2de0e6545.png)

**Comment by sstolk90** [comment]
Like this: 
![image](https://user-images.githubusercontent.com/65487781/233789793-9706657e-ae16-4eb0-bae7-1e8a92c95241.png)
I get not any confirmation and the Growatt is still producing more then the limit. 
Is this implemented after 20 aug 2022?

**Comment by joe288** [comment]
this was added to the master branch of nygma2004 on 10 December.
![image](https://user-images.githubusercontent.com/20052129/233796790-49a6db8f-c54a-459f-823d-ecf38dbe04f9.png)

**Comment by sstolk90** [comment]
Thanks! So it is not in my sketch yet and that's why it won't scale down when instructed to.
I cannot update the sketch since Arduino IDE is bugging me big time but that is not part of this issue.
I get lots of errors for a FastLED and a lot more of definitions from certain files he cannot find.

Issue can be closed and thanks for your help!
