### ISSUE TITLE
unable to use setMaxOutput

### ISSUE THREAD

**Issue by MichaLUE** [nygma2004/growatt2mqtt#30]
Hi,
what must i change in code to use

topicroot/write/setMaxOutput | subscribe | 0-100 | set the output level of the growatt in percent 

as described in documentation?

Micha.

**Comment by nygma2004** [comment]
What do you mean? You need to send a value from 0 to 100 to topic <base topic>/write/setMaxOutput. That's all. Nothing needs to be enabled.

**Comment by MichaLUE** [comment]
Hi, so I have to create "topicroot/write/setMaxOutput" in my MQTT server and set MaxOutput with a char? Then the D1 reads it and sends it to the inverter?

Sorry I'm not that smart on this topic.

**Comment by nygma2004** [comment]
Yes, there is a roottopic variable in settings.h which is set to growatt be default. So the topic would be growatt/write/setMaxOutput. And yes send in the number 0-100, it is received by D1, and is sent to the inverter.

**Comment by MichaLUE** [comment]
Wow, it works!!!
Many thank for your answers. :-)
