### ISSUE TITLE
Wifi does not connect

### ISSUE THREAD

**Issue by Alexbuehs** [nygma2004/growatt2mqtt#4]
I am a newcomer to the field, I flashed the ESP with the code via Arduino. I made the setting under Settings.h but unfortunately the ESP does not connect to the Wifi after flashing. Can you maybe help me and tell me where exactly I have to set what in the Settings.h tab?
![C7223C36-6E86-4875-AB43-B1303A20EA7C](https://user-images.githubusercontent.com/86471233/173578890-c6462c96-d5b1-414f-9036-a22a61204283.png)

**Comment by nygma2004** [comment]
You need to change all the x-es to the actual values in your system: SSID, password, MQTT server IP address, userid and password.

**Comment by Alexbuehs** [comment]
![94B179AB-C9E6-4B3B-AFB9-8DC31C3A6B54](https://user-images.githubusercontent.com/86471233/173602153-959e52c0-22bc-428e-8e65-40b980bed6b8.jpeg)

**Comment by nygma2004** [comment]
You can leave it as it is. The ESP will just get a dynamic IP address, it will not impact how it works.

**Comment by Alexbuehs** [comment]
First of all, thank you very much for your help. That's exactly how I did it and the esp was flashed without any problems but when I then open the serial monitor there is always WIFI Connecting .............. and that repeats itself again and again. If the esp is flashed, the blue LED also lights up permanently, is that correct?

**Comment by nygma2004** [comment]
Yes, the blue is on until it connects to the wifi, and from that point it only flashes when reads the inverter. Can you screenshot the current settings.h file (obviously blurring out the passwords) and the full serial log? Maybe that will give me some ideas on what is going on.

**Comment by Alexbuehs** [comment]
I will take a screenshot of settings.h tomorrow and post here. Thanks again for your help.

**Comment by Alexbuehs** [comment]
Hey, I realised that the code is running. I deleted your code from the computer again. Then I re-downloaded your code again in Arduino opened the x-es replaced and flashed. The ESP now connects to the Wifi. Now I just have to see that I can do it with the broker. Do that with a raspberry and the iobroker but in the data point it only says true. Is there another way to even see if the esp receives data? I connected all this to a Growatt TL-X.

**Comment by Alexbuehs** [comment]
And one more question. Does the Wifi Shine X Stick have to be unplugged?

**Comment by nygma2004** [comment]
Check the serial debugger. If it is not able to read the inverter, you get some error messages (like No Response or similar). So if you see no error, the modbus is working.
I think the Shine X plugs into a different port, so you can leave it. I don't have that.

**Comment by Alexbuehs** [comment]
How do I get the serial debugger via wifi? Or leave the esp connected to the pc and then via the serial monitor from Arduino?

**Comment by nygma2004** [comment]
Yes, use it connected to the computer and user the serial monitor from Arduino IDE.
