### ISSUE TITLE
Used housing?

### ISSUE THREAD

**Issue by no-Legend** [nygma2004/growatt2mqtt#8]
Can you tell us which housing you designed the pub for?

Cheers Robert

**Comment by nygma2004** [comment]
Sorry, I don't get it. Pub?

**Comment by unimatrixZxero** [comment]
I think the question is asking. "What housing did you use to put the PCB in?" Or, what's the housing you used to put the components in?

**Comment by nygma2004** [comment]
I used a regular electrical box I could find in my local shop. This is one of the harder shell models. I cut an opening on the top and added a window with a piece of acrylic.
I think it was this: https://daniella.hu/sez-kotodoboz-s-box-216-sima-falu-120x80x50-id-sez1001081000
It is hard to find transparent top enclosures.
